# Generated by Django 3.0.6 on 2021-01-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('plantId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='pictures/')),
                ('quantity', models.PositiveIntegerField()),
                ('sellerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.Nursery')),
            ],
            options={
                'db_table': 'Plants',
            },
        ),
    ]
