# Generated by Django 3.0.6 on 2021-01-06 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20210104_1921'),
        ('nursery', '0001_initial'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 14, 38, 36, 517200, tzinfo=utc))),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Plants')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.Nursery')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
